### PR TITLE
nesting files in subdir for getNewTempFile

### PR DESCRIPTION
**Pull request by miki725**
Some apps such as `docker` when installed via `snap` dont have permissions to access temporary files created directly in `/tmp` but crucially can access them when nested inside another folder inside `/tmp`.

This changes `getNewTempFile()` function to create temporary file inside a nested directory inside the temp location whatever that might be as determined by `genTempPath` which will honor things like `TMPDIR`/etc

This resolves docker permission issues but still leaves tmp location to be default as determined by the OS/user

@indecisivedragon was able to test it on her Ubuntu linux instance which has docker installed with snap

### CODE REVIEW

**Comment by viega** [comment]
Does it even need to be an option? Or, at least, having it on by default doesn't seem like it could hurt, right?

**Comment by miki725** [comment]
we could make it the default. guess it was a style choice as paths read funny like `/tmp/chalk.abc.file/chalk.xyz.file` but yeah we can make it default

**Comment by miki725** [comment]
updated default behavior

**Review by viega — APPROVED** [review]
If you think the longer paths are ugly when not needed, I can get behind that too I suppose. Either way, you're good to merge when you want.

**Comment by miki725** [comment]
it was visually a bit annoying but I think simplicity of usage is more important. otherwise the caller needs to know some specifics about temp files vs rather just "give me temp file". those paths are not meant to be human readable anyhow so its prolly fine

**Comment by viega** [comment]
That was exactly why it was my preference, good show :)

**Pull request merged**
